<div id="view-content">
	<div class="container">
		<div class='row'>	
			<div class="span5">
				<div class="form-box">
					<div class="form-body">
						<legend>Add Category</legend>
						<?php 
							echo $this->form;
							echo "<a class= 'btn btn-info' href='index'>View All Categories</a>";
						?>
					</div>
				</div>
			</div>
			<div class="span7">
				<div class="form-box">
					<div class="form-body">
						<legend>Existing Categories</legend>
						<div class="gallery" style="bachground-color:black">
						<?php 
							echo "<ul class='row'>";
							foreach ($this->Allcats as $cat) {
								echo "<li class='btn btn-primary'> <a style='color:#F5F5F5;' href='category/single/".$cat['id']."'>".$cat['name']."</a></li> ";
							}
							echo "</ul>";
						?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

