<div id="view-content">
	<div class="container">
        	<div class="row">
            	<div class="span8">
                	<div class="profile-box editing">
                        <?= $this->form ?>
                        <a class='btn btn-info' href=<?= $this->baseUrl()?>/category/index >back to list</a> 
                    </div>
                </div>
            </div>
        </div>
</div>

