<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span#zf-name
    {
        color: #91BE3F;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-image: url(http://framework.zend.com/images/bkg_header.jpg);
        width:  600px;
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(http://framework.zend.com/images/bkg_body-bottom.gif);
        height: 100%;
    }
    #jumb
    {
    color: floralwhite;
    padding: 70px 30px;
    margin: 0px auto;
    background: #0C3E56;
    }
</style>
<div class="wrapper">
    <!--BANNER START-->
    <div class="banner">
<!--         <div class="bx-wrapper" style="max-width: 100%;"><div class="bx-viewport" style="width: 100%; overflow: hidden; position: relative; height: 630px;"><ul class="bxslider" style="width: auto; position: relative;">
          <li style="float: none; list-style: none; position: absolute; display: none; z-index: 0; width: 1288px;"><img src="images/banner1.jpg?timestamp=1463187895249" alt=""> </li>
          <li style="float: none; list-style: none; position: absolute; z-index: 0; display: none; width: 1288px;"><img src="images/banner2.jpg" alt=""></li>
          <li style="float: none; list-style: none; position: absolute; z-index: 0; display: none; width: 1288px;"><img src="images/banner3.jpg" alt=""></li>
          <li style="float: none; list-style: none; position: absolute; z-index: 50; width: 1288px;"><img src="images/banner4.jpg" alt=""></li>
        </ul></div><div class="bx-controls bx-has-pager bx-has-controls-direction"><div class="bx-pager bx-default-pager"><div class="bx-pager-item"><a href="" data-slide-index="0" class="bx-pager-link">1</a></div><div class="bx-pager-item"><a href="" data-slide-index="1" class="bx-pager-link">2</a></div><div class="bx-pager-item"><a href="" data-slide-index="2" class="bx-pager-link">3</a></div><div class="bx-pager-item"><a href="" data-slide-index="3" class="bx-pager-link active">4</a></div></div><div class="bx-controls-direction"><a class="bx-prev" href=""></a><a class="bx-next" href=""></a></div></div></div> -->
            <div  class="container-fluid">
                <div class="row row-header">
                <div id='jumb'>
                    <div class="col-xs-12 col-sm-8">
                        <h1>Learning Management System</h1>
                        <p style="padding:60px;"></p>
                        <p>Fine online courses on Web development, Yoga, Guitar lessons, or anything else.</p>
                    </div>
                    <div class="col-xs-12 col-sm-4">
                    </div>
                    </div>
                </div>
            </div>
    <!--BANNER END-->
    <!--CONTANT START-->
    <div class="contant">
        <!--SERVICES SECTION START-->
        <section>
            <div class="container">
                <!--SECTION HEADER START-->
                <div class="sec-header">
                    <h2>Our Services</h2>
                    <p>Take a look at what we have are doing</p>
                </div>
                <!--SECTION HEADER END-->
                <div class="row">
                    <!--SERVICE ITEM START-->
                    <div class="span4">
                        <div class="services">
                            <div class="header">
                                <i class="fa fa-tablet"></i>
                                <i class="fa fa-user inner-icon"></i>
                            </div>
                            <div class="text">
                                <h3><a href="#">Expert teachers</a></h3>
                                <p>UI improvements were the one aspect of WordPress's future that everyone I spoke to seemed to agree on: </p>
                            </div>
                        </div>
                    </div>
                    <!--SERVICE ITEM END-->
                    <!--SERVICE ITEM START-->
                    <div class="span4">
                        <div class="services">
                            <div class="header">
                                <i class="fa fa-tablet"></i>
                                <i class="fa fa-list-alt inner-icon"></i>
                            </div>
                            <div class="text">
                                <h3><a href="#">Trusted certifications</a></h3>
                                <p>UI improvements were the one aspect of WordPress's future that everyone I spoke to seemed to agree on: </p>
                            </div>
                        </div>
                    </div>
                    <!--SERVICE ITEM END-->
                    <!--SERVICE ITEM START-->
                    <div class="span4">
                        <div class="services">
                            <div class="header">
                                <i class="fa fa-tablet"></i>
                                <i class="fa fa-cogs inner-icon"></i>
                            </div>
                            <div class="text">
                                <h3><a href="#">Start Learning</a></h3>
                                <p>UI improvements were the one aspect of WordPress's future that everyone I spoke to seemed to agree on: </p>
                            </div>
                        </div>
                    </div>
                    <!--SERVICE ITEM END-->
                </div>
            </div>
        </section>
        <div class="copyright">
            <div class="container">
                <p>© Copyrights 2015. Zend ITI</p>
            </div>
        </div>
    </footer>
    <!--FOOTER END-->
</div>
</div>