<!--BANNER END-->
<div class="course-detail" style="background:cadetblue;">
<div class="container">
<div class="row">
<div class="span4">
<div class="profile-box profile-view">
	<div class="thumb">
	    <a href="#"><img src=<?php echo $this->baseUrl().'/images/courses/'.$this->course[0]['image'] ?>></a>
	</div>
</div>	
</div>
<div class="span6">
	<div class="text">
    	<h2><?php echo $this->course[0]['name'] ?></h2>
        <h5></h5>
        <div clas='row'>
        <table class='span5'>
        	<tr>
        	<textarea rows="7"><?php echo $this->course[0]['summary']?></textarea>
        	</tr>
        </table>
        </div>
    </div>
</div>
</div>
</div>
</div>
<!--CONTANT START-->
<div class="contant">
<div class="container">
<div class="row">
<div class="span9">
	<div class="featured-courses">
	<?php 
		if(!empty($this->courseM)){
	?>
    	<h2>Browsing All Matrials</h2>
    	<div class="row">
    	<?php
    		foreach ($this->courseM as $cm) {
    		}
    		if($cm['is_hidden'] == '0'){
    	?>
        	<div class="span3">
            	<div class="course">
                    <div class="text">
                        <div class="header">
                            <h4><?php echo "<a href='".$this->baseUrl()."/materials/single/id/".$cm['id']."'>".$cm['name']."</a>"  ?> <span class='badge'><?php echo $cm['type']?></span></h4>
                            <div class="well">
                                <span class='badge'>Number of downloads <?php echo $cm['num_downloads'] ?></span>
                            </div>
                        </div>
                       <?php if($cm['is_locked'] == '0'){
                       ?>
                        <div class="course-detail-btn">
                            <a href=<?php echo $this->baseUrl().'/materials/'.$cm['path'] ?>>View</a>
                            <a href=<?php echo $this->baseUrl().'/materials/download/id/'.$cm['id'] ?>>Download</a>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>
        <?php 
    	}
    }
        ?>
    </div>
</div>

     