
<!-- <div id="view-content">
	<p>View script for controller <b>Materials</b> and script/action name <b>index</b></p>
</div> -->
<?php
	foreach ($this->materials as $material){
		if ($material['is_hidden']== "0" ) {
			show($material,$this->baseUrl());
		}
		// elseif ($this->identity->role == "1") {
		// 	show($material,$this);
		// }
}
function show($material,$path)
{
	echo "<label> ID: </label>".$material['id'].'<br />';
	// echo "<label> User ID: </label>".$material['user_id'].'<br />';
	echo "<label> Name: </label><a href='".$path."/materials/single/id/".$material['id']."'>".$material['name'].'</a><br />';
	echo "<label> Type: </label>".$material['type'].'<br /><br />';
	echo "<label> User ID: </label>".$material['user_id'].'<br /><br />';
	echo "<label> Course ID: </label>".$material['course_id'].'<br /><br />';
	echo "<label> Number of downloads: </label>".$material['num_downloads'].'<br /><br />';
	echo "<label> Is_Locked: </label>".$material['is_locked'].'<br /><br />';
	echo "<label> Is_Hidden: </label>".$material['is_hidden'].'<br /><br />';
	echo "<label> Time_Added: </label>".$material['time'].'<br /><br />';
	echo "<a href='".$path."/materials/download/name/".$material['path']."'>Download the material</a><br />";
	echo "<a href='".$path."/materials/edit/id/".$material['id']."'> Edit </a> "."<a href='".$path."/materials/delete/id/".$material['id']."'> Delete </a> <br />";
	echo str_repeat('*', 100).'<br />';
}
