<div id="view-content">
<div class="container">
	<div class="row">
		<div class="follow-us">
			<table class="table">
				<th>ID</th>
				<th>Name</th>
				<th>Type</th>
				<th>User ID</th>
				<th>Course ID</th>
				<th>Num. Downloads</th>
				<th>is Locked</th>
				<th>is Hidden</th>
				<th>Date</th>

<?php

	foreach ($this->materials as $material){
		if ($material['is_hidden']== "0" ) {
			show($material,$this->baseUrl());
		}
		elseif ($this->identity->role == "1") {

			show($material,$this->baseUrl());

		}
}
function show($material,$path)
{
	echo "<tr><td>".$material['id'].'</td>';
	// echo "<label> User ID: </label>".$material['user_id'].'<br />';

	echo "<td><a href='".$path."/materials/single/id/".$material['id']."'>".$material['name'].'</a></td>';
	echo "<td>".$material['type'].'</td>';
	echo "<td>".$material['user_id'].'</td>';
	echo "<td>".$material['course_id'].'</td>';
	echo "<td>".$material['num_downloads'].'</td>';
	echo "<td>".$material['is_locked'].'</td>';
	echo "<td>".$material['is_hidden'].'</td>';
	echo "<td>".$material['time'].'</td>';
	echo "<td><a  class= 'btn btn-primary' href='".$path."/materials/download/id/".$material['id']."'>Download</a></td>";
	echo "<td><a class='btn btn-info' href='".$path."/materials/edit/id/".$material['id']."'> Edit </a></td> "."<td><a class='btn btn-danger' href='".$path."/materials/delete/id/".$material['id']."'> Delete </a></td> ";
	echo "<td><a href='".$path."/materials/show/id/".$material['id'].($material['is_hidden'] == "0" ?  "'  class='btn btn-danger' > Hide </a> </td>": "' class='btn btn-success'> Show </a> ");
	
	echo "<td><a href='".$path."/materials/lock/id/".$material['id'].($material['is_locked'] == "0" ?  "' class = 'btn btn-danger'> Lock </a> ": "' class = 'btn btn-success'> Unlock </a> ")."</td></tr>";

}

?>
</div>
