<br /><br />
<div id="view-content">
<?php
	$material = $this->material;
	// echo "<label> ID: </label>".$material['id'].'<br />';
	// echo "<label> User ID: </label>".$material['user_id'].'<br />';
	echo "<label> Name: </label><p>".$material['name'].'</p><br />';
	echo "<label> Type: </label>".$material['type'].'<br /><br />';
	// echo "<label> User ID: </label>".$material['user_id'].'<br /><br />';
	echo "<label> Course Name: </label>".$this->course.'<br /><br />';
	echo "<label> Number of downloads: </label>".$material['num_downloads'].'<br /><br />';
	// echo "<label> Is_Locked: </label>".$material['is_locked'].'<br /><br />';
	// echo "<label> Is_Hidden: </label>".$material['is_hidden'].'<br /><br />';
	echo "<label> Time_Added: </label>".$material['time'].'<br /><br />';
	if ($material['is_locked'] == "0") {
	echo "<a href='".$this->baseUrl()."/materials/download/id/".$material['id']."'>Download the material</a><br />";

	}
	
	echo "<br/> ";
	// if ($this->identity->role == "1") {
		echo "<a href='".$this->baseUrl()."/materials/edit/id/".$material['id']."'> Edit </a> "."<a href='".$this->baseUrl()."/materials/delete/id/".$material['id']."'> Delete </a> <br />";
		echo "<a href='".$this->baseUrl()."/materials/show/id/".$material['id'].($material['is_hidden'] == "0" ?  "'> Hide </a> ": "'> Show </a> ");
		
		echo "<a href='".$this->baseUrl()."/materials/lock/id/".$material['id'].($material['is_locked'] == "0" ?  "'> Lock </a> ": "'> Unlock </a> ");
	// }

	echo  "<br/><h3>Comments</h3>";

	foreach ($this->comments as  $comment) {
		$user_obj = new Application_Model_DbTable_User();
		$user = $user_obj->getUserById($comment['user_id'])[0];
		echo "<a href='".$this->baseUrl()."/users/profile/id/".$user['id']."'>".$user['full_name']."</a><br/>&nbsp&nbsp&nbsp&nbsp&nbsp";
		echo $comment['content']."&nbsp&nbsp&nbsp&nbsp&nbsp";
		if ($this->identity->id == $comment['user_id']) {
			echo "<a href='".$this->baseUrl()."/comments/edit/id/".$comment['id']."/material_id/".$material['id']."'> Edit </a> "."<a href='".$this->baseUrl()."/comments/delete/id/".$comment['id']."/material_id/".$material['id']."'> Delete </a> ";
		}
		echo "<br />";
		
	}
?>
<form action="<?= $this->baseUrl() ?>/comments/add" method="post" >
	<textarea name="content"></textarea>
	<input type="hidden" name="material_id" value="<?= $material['id'] ?>" />
	<input type="hidden" name="user_id" value="<?= $this->identity->id ?>" />
	<input type="submit" name="submit" value="Add Comment" />
</form>
	
	
</div>