<div id="view-content">
	<div class="container">
		<div class='row'>	
			<div class="span8">
				<div class="form-box">
					<div class="form-body">
					<form action =<?php echo $this->baseUrl()."/users/request"?> method="post">
						<label>Your message</label>
						<input class='form-control' type='textarea' name='content' > </input>
						<input class='btn btn-primary' type='submit' value="submit"></input>
					</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
