
<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
</head>
<body>
<!--WRAPPER START-->
<div class="wrapper">
    <!--HEADER START-->
    <header>
    	<!--TOP STRIP START-->
        <div class="top-strip">
        	<div class="container">
                <!--ACCOUNT SECTION START-->
                <div class="account">
                	<ul>
                    	<li><a href="#">Subscribe</a></li>
                        <li><a href=<?= $this->baseUrl()."/users/signout"?>>Sign Out</a></li>
                        <li>
                        	<div class="dropdown">
                                <a class="dropdown-toggle" id="account" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                                My Account
                                <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="account">
                                    <li><a href="#">Profile</a></li>
                                    <li><a href="#">Account Setting</a></li>
                                    <li><a href="#">Privacy Setting</a></li>
                                </ul>
                            </div>
                        </li>
                    </ul>
                </div>
                <!--ACCOUNT SECTION START-->
            </div>
        </div>
        <!--TOP STRIP END-->
        <!--NAVIGATION START-->
        <div class="navigation-bar">
        	<div class="container">
            	<div class="logo">
                	<a href="index.html"><img src="/zendSLMS/public/images/logo.png" alt=""></a>
                </div>
                <div class="navigation">
					<div class="navbar">
					  <div class="navbar-inner" >
						<div class="container">
						  <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						  <div class="nav-collapse collapse">
							<ul>
								<li><a href="javascript:void(0)">Home</a>
									<ul>
                                    	<li><a href="index.html">Home Page Default</a></li>
                                    	<li><a href="index-1.html">Home Page 1</a></li>
                                        <li><a href="index-2.html">Home Page 2</a></li>
                                        <li><a href="index-3.html">Home Page 3</a></li>
                                        <li><a href="index-4.html">Home Page 4</a></li>
                                        <li><a href="index-sidemenu.html">Home Page 5</a></li>
                                    </ul>
								</li>
								<li><a href="javascript:void(0)">Blog</a>
									<ul>
										<li><a href="blog.html">Blog</a></li>
										<li><a href="blog-detail.html">Blog Detail</a></li>
									</ul>
								</li>
								<li><a href="services.html">Services</a></li>
								<li><a href="javascript:void(0)">Events</a>
									<ul>
										<li><a href="events.html">Events</a></li>
										<li><a href="events-detail.html">Event Detail</a></li>
									</ul>
								</li>
								<li><a href="javascript:void(0)">Courses</a>
									<ul>
										<li><a href="courses.html">Courses</a></li>
										<li><a href="courses-detail.html">Course Detail</a></li>
									</ul>
								</li>
								<li><a href="javascript:void(0)">Pages</a>
									<ul>
										<li><a href="about-us.html">About us</a></li>
										<li><a href="404.html">Error 404</a></li>
										<li><a href="faq.html">FAQs</a></li>
										<li><a href="gallery.html">Gallery</a></li>
										<li><a href="news.html">News</a></li>
										<li><a href="our-lessons.html">Our Lessons</a></li>
										<li><a href="search-result.html">Search Result</a></li>
										<li><a href="signin.html">Sign In</a></li>
										<li><a href="student-login.html">Student Login</a></li>
										<li><a href="student-profile.html">Student Profile</a></li>
										<li><a href="teacher-profile.html">Teacher Profile</a></li>
										<li><a href="team.html">Our Team</a></li>
										<li><a href="edit-profile.html">Edit Your Profile</a></li>
									</ul>
								</li>
								<li><a href="contact-us.html">Contact Us</a></li>
							</ul>
						  </div>
						</div>
					  </div>
					</div>
				</div>
            </div>
        
       </div>
</div>
        <!--NAVIGATION END-->
    </header>
    <!--HEADER END-->

<?php echo $this->layout()->content; ?>

<?php echo $this->headScript() ?>
</body>
</html>
