<?php echo $this->doctype();
$identity = Zend_Auth::getInstance()->getIdentity();
?>
<html>
<head>
<?php echo $this->headMeta(); ?>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->headTitle() ?>
<?php echo $this->headLink() ?>
</head>
<body>
<!--WRAPPER START-->
<div class="wrapper">
    <!--HEADER START-->
    <header>
    	<!--TOP STRIP START-->
        <div class="top-strip">
        	<div class="container">
                <!--ACCOUNT SECTION START-->
                <div class="account">
                	<ul>
                	<?php
                		if(!isset($identity)){
					?>
                    	<li><a href=<?= $this->baseUrl()."/users/register"?>>Sign Up</a></li>
 					 <?php
                    	}
                    ?>
                    <?php
                		if(isset($identity)){
					?>
                        <li><a href=<?= $this->baseUrl()."/users/signout"?>>Sign Out</a></li>
                     
                        <li>
                        	<div class="dropdown">
                                <a class="dropdown-toggle" id="account" role="button" data-toggle="dropdown" data-target="#" href="/page.html">
                                My Account
                                <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="account">
                                    <li><a href=<?=$this->baseUrl()."/users/profile/id/".$this->identity->id?>>Profile</a></li>
                                    <li><a href=<?=$this->baseUrl()."/users/update/id/".$this->identity->id?>>Update Profile</a></li></ul>
                            </div>
                            <?php
              			}
						?>
                        </li>
                    </ul>
                </div>
                <!--ACCOUNT SECTION START-->
            </div>
        </div>
        <!--TOP STRIP END-->
        <!--NAVIGATION START-->
        <div class="navigation-bar">
        	<div class="container">
            	<div class="logo">
                	<a href=<?php echo $this->baseUrl()."/index/index"?>><img src="/zendSLMS/public/images/logo.png" alt=""></a>
                </div>
                 <?php
              if(isset($this->identity)){
		?>
                <div class="navigation">
					<div class="navbar">
					  <div class="navbar-inner" >
						<div class="container">
						  <button data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar" type="button">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						  </button>
						  <div class="nav-collapse collapse">
							<ul>
                            	<li><a href=<?= $this->baseUrl()."/index/index"?>>Home</a></li>
								</li>
									<li><a href="blog.html">Send Request</a></li>
									<li><a href="services.html">Activity Log</a></li>
									<li><a href="events.html">Materials</a></li>
								</li>
								<li>	<a href=<?= $this->baseUrl()."/course/list"?>>Courses</a>
								</li>
								</li>
							</ul>
							<?php if($this->identity->role == '1'){
								?>
							<ul>
							<li><a href="javascript:void(0)">Admin</a>
									<ul>
										<li><a href=<?= $this->baseUrl()."/users/list"?>>Users</a></li>
										<li><a href=<?= $this->baseUrl()."/course/index"?>>Courses</a></li>
										<li><a href=<?= $this->baseUrl()."/category/index"?>>Categorise</a></li>
										</li>
									</ul>
								</li>
								</ul>
								<?php
							}
								?>
						  </div>
						</div>
					  </div>
					</div>
				</div>
				 <?php
              }
		?>
            </div>
        
       </div>
      
</div>
        <!--NAVIGATION END-->
    </header>
    <!--HEADER END-->

<?php echo $this->layout()->content; ?>

<?php echo $this->headScript() ?>
</body>
</html>
