<div class="view-content">
	<div class="container">
		<div class='row'>
			<div class="error">
                <p class="error-404">4<span><img src="/zendSLMS/public/images/error.png" alt=""></span>4</p>
                <p class="ohh">Uh Oh! Looks like something broke.</p>
                <p class="away">Take me away <span class="color">or</span> Report This</p>
			</div>
		</div>
	</div>
</div>		